src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use AppBundle\Lib\Enumeration\Active;
use AppBundle\Lib\Enumeration\City;
use AppBundle\Lib\Enumeration\Gender;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 */
class User
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var bool
     *
     * @ORM\Column(name="sex", type="boolean")
     */
    private $sex;

    /**
     * @var int
     *
     * @ORM\Column(name="city", type="integer")
     */
    private $city;

    /**
     * @var bool
     *
     * @ORM\Column(name="active", type="boolean")
     */
    private $active;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return User
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set sex
     *
     * @param boolean $sex
     *
     * @return User
     */
    public function setSex($sex)
    {
        $this->sex = $sex;

        return $this;
    }

    /**
     * Get sex
     *
     * @return bool
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * Set city
     *
     * @param integer $city
     *
     * @return User
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return int
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set active
     *
     * @param boolean $active
     *
     * @return User
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return bool
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * @return string
     */
    public function getPrintTableSex()
    {
        return Gender::getALL()[$this->sex];
    }

    /**
     * @return string
     */
    public function getPrintTableCity()
    {
        return City::getALL()[$this->city];
    }

    /**
     * @return string
     */
    public function getPrintTableActive()
    {
        return Active::getALL()[$this->active];
    }
}

src/AppBundle/Form/UserType.php
<?php

namespace AppBundle\Form;

use AppBundle\Lib\Enumeration\Active;
use AppBundle\Lib\Enumeration\City;
use AppBundle\Lib\Enumeration\Gender;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::class,[
            'label'=>"Имя:"
        ]);
        $builder->add('lastName', TextType::class,[
            'label'=>"Фамилия:"
        ]);
        $builder->add('email', EmailType::class,[
            'label'=>"E-mail:"
        ]);
        $builder->add('password', PasswordType::class,[
            'label'=>'Пароль:'
        ]);
        $builder->add('sex', ChoiceType::class,[
            'label'=>'Пол:',
            'choices'=>Gender::getALL(true),
            'expanded'=>true,
        ]);
        $builder->add('city', ChoiceType::class,[
            'label'=>'Город:',
            'choices'  => City::getALL(true),
        ]);
        $builder->add('active', ChoiceType::class, [
            'label'=>'Активный:',
            'choices'  => Active::getALL(true),
            'expanded'=>true
        ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {

    }

    public function getBlockPrefix()
    {
        return 'app_bundle_user_type';
    }
}

src/AppBundle/Controller/UserController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\User;
use AppBundle\Form\UserType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;

class UserController extends Controller
{
    /**
     * @Route("/", name="userList")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->findAll();
        $delete_form = $this->createFormBuilder()
            ->add('delete', SubmitType::class, ['label' => 'Удалить'])
            ->setMethod('DELETE')
            ->getForm();

        return $this->render('@App/user/index.html.twig',[
            'users'=>$users,
            'articleDeleteForm' => $delete_form
        ]);
    }
    /**
     * @Route("/user/new", name="userNew")
     * @Method({"GET","HEAD","POST"})
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function newAction(Request $request)
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user, [
            'method' => 'POST'
        ])->add('save', SubmitType::class, ['label' => 'Добавить']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute("userList");
        }
        return $this->render('@App/user/new.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/user/{id}/edit", requirements={"id": "\d+"}, name="userEdit")
     * @Method({"GET","HEAD","PUT"})
     * @param Request $request
     * @param integer $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, int $id)
    {
        $user = $this->getDoctrine()
            ->getRepository('AppBundle:User')
            ->find($id);
        $form = $this->createForm(UserType::class, $user, [
            'method' => 'PUT'
        ])->add('save', SubmitType::class, ['label' => 'Сохранить']);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute("userList");
        }
        return $this->render('@App/user/new.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/user/{id}/delete", requirements={"id": "\d+"},name="userDelete")
     * @Method({"DELETE"})
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function deleteAction(int $id)
    {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->find($id);

        $em = $this->getDoctrine()->getManager();
        $em->remove($user);
        $em->flush();

        return $this->redirectToRoute("userList");
    }
    /**
     * @Route("/user/{id}/show", requirements={"id": "\d+"},name="userShow")
     * @Method({"GET","HEAD"})
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction(int $id)
    {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->find($id);
        $delete_form = $this->createFormBuilder()
            ->add('delete', SubmitType::class, ['label' => 'Удалить'])
            ->setMethod('DELETE')
            ->getForm();
        return $this->render('@App/user/show.html.twig',[
            'user'=>$user,
            'articleDeleteForm' => $delete_form
        ]);
    }

}

src/AppBundle/Resources/views/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Редактирование пользователя</h1>
    {{ include('@App/user/user_form.html.twig', { 'form': form }) }}
{% endblock %}

src/AppBundle/Resources/views/user/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Список пользователей</h1>
<a href="{{ path('userNew') }}"><button>Добавить пользователя</button></a><br><br>
<table width="600px" border="1">
    <thead>
    <tr>
        <th>Имя:</th>
        <th>Фамилия:</th>
        <th>Email:</th>
        <th>Действие</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr onclick="window.location='{{ path('userShow',{'id':user.id})}}'">
            <td>{{ user.name }}</td>
            <td>{{ user.lastName }}</td>
            <td>{{ user.email }}</td>
            <td>
                <a href="{{ path('userEdit', {'id' : user.id}) }}"><button>Редактировать</button></a>
                {% set form = articleDeleteForm.createView %}
                {{ form_start(form, {'action' : path('userDelete', {'id' : user.id})}) }}
                {{ form_widget(form) }}
                {{ form_end(form) }}

            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="4">Нет пользователей</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

src/AppBundle/Resources/views/user/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Добавление пользователя</h1>
    {{ include('@App/user/user_form.html.twig', { 'form': form }) }}
{% endblock %}

src/AppBundle/Resources/views/user/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Пользователь: {{ user.name }} {{ user.lastName }} {{ user.email }}</h1>
    <table width="600px" border="1">
        <thead>
        <tr>
            <th>Имя:</th>
            <th>Фамилия:</th>
            <th>Email:</th>
            <th>Пол:</th>
            <th>Город:</th>
            <th>Активный:</th>
            <th>Действие:</th>
        </tr>
        </thead>
        <tbody>
            <tr onclick="window.location='{{ path('userShow',{'id':user.id})}}'">
                <td>{{ user.name }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.printTableSex }}</td>
                <td>{{ user.printTableCity }}</td>
                <td>{{ user.printTableActive }}</td>
                <td>
                    <a href="{{ path('userEdit', {'id' : user.id}) }}"><button>Редактировать</button></a>
                    {% set form = articleDeleteForm.createView %}
                    {{ form_start(form, {'action' : path('userDelete', {'id' : user.id})}) }}
                    {{ form_widget(form) }}
                    {{ form_end(form) }}
                </td>
            </tr>
        </tbody>
    </table>
    <br><br> <a href="{{ path('userList') }}"><button>К списку пользователей</button></a><br><br>
{% endblock %}

src/AppBundle/Resources/views/user/user_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}
<br><br> <a href="{{ path('userList') }}"><button>К списку пользователей</button></a><br><br>